// credit : https://codeforces.com/blog/entry/96040?#comment-851247
#include <iostream>
#include <compare>

struct Fraction {
    int p, q;

    Fraction (int _p, int _q) : p(_p), q(_q) {
    }

    std::strong_ordering operator<=> (const Fraction &oth) const {
        return p * oth.q <=> q * oth.p;
    }
};


int main () {
   Fraction u (1, 3);
   Fraction v (2, 5);

   // all these are automatically generated by the compiler!
   std::cout << (u < v) << std::endl;
   std::cout << (u > v) << std::endl;
   std::cout << (u <= v) << std::endl;
   std::cout << (u >= v) << std::endl;
}